export default {
  sections: ['cover', 'teachers', 'pupils', 'group', 'reportage'],

  comments: [
    {
      title: 'Съемка назначена',
      content:
        'Съемка по вашему договору назначена. Не забудьте ознакомиться с информацией по съемке – она была выслана Вам на почту, а также заполнить необходимую информацию о моделях на съемке',
    },
    {
      title: 'Назначить доп. Съемку',
      content:
        'Необходимо как можно скорее назначить дополнительную съемку с куратором отдела фотографов.',
    },
    {
      title: 'Доп. Съемка назначена',
      content:
        'Дополнительная съемка по вашему договору назначена. Ожидайте день съемки, наш фотограф предварительно с Вами свяжется за день.',
    },
    {
      title: 'Подготовка фотографий',
      content:
        'Все съемки по Вашему договору проведены. Фотограф подготавливает материал для выгрузки в лк.',
    },
    {
      title: 'Заказ на формировании',
      content:
        'В течение 7-ми календарных дней, вам необходимо предоставить недостающий материал, чтобы не нарушать сроков, указанных в договоре.',
    },
    {
      title: 'Заказ в отделе дизайна',
      content:
        'Ваш заказ передан в Отдел Дизайна. В течение 20 рабочих дней Вам будет выслан предварительный макет.',
    },
    {
      title: 'Заказ на сверке у клиента',
      content:
        'Макет альбома направлен в разделе Сверка макета. Очень ждем правки! Обращаем Ваше внимание на то, что список правок можно прислать дизайнеру не более трёх раз. Большая просьба высылать правки оперативно, чтобы не растягивать сроки.',
    },
    {
      title: 'Заказ на правках',
      content:
        'В макет вносятся правки, которые Вы прислали. Скоро пришлем исправленный вариант.',
    },
    {
      title: 'Заказ загружен в производство',
      content:
        'Вы подтвердили заказ  в печать. В течение 10 рабочих дней он будет готов. По готовности наши сотрудники позвонят Вам для назначения доставки.',
    },
    {
      title: 'Заказ готов',
      content: 'Ваш заказ находится в офисе. Ожидайте звонка от специалиста.',
    },
  ],

  designs: [
    'rainbow',
    'forbesGray',
    'forbesBlue',
    'forbesBrown',
    'people',
    'retro',
    'urban',
    'emerald',
    'boysGirls',
    'leafFall',
    'bell',
    'wantedRed',
    'oldMoscow',
    'filmBlue',
    'filmBrown',
    'londonRed',
    'londonPurple',
    'londonBlue',
    'dreamsPurple',
    'plan',
    'chalkDarkGreen',
    'chalkBlack',
    'pegasusBlue',
    'pegasusBrown',
    'owls',
    'school',
    'mgmsu',
    'mgimo',
    'mvd',
    'gitis',
    'rgsuGas',
    'mgtu',
    'mgu',
    'mchs',
    'vshe',
    'rta',
    'guu',
    'rapDarkBlue',
    'rapBeige',
    'fable',
    'fantasy',
    'summer',
    'star',
    'maple',
    'numbers',
    'zodiac',
    'release',
    'quarter',
    'oldPiter',
    'monochrome',
    'comics',
    'vmf',
    'reportageDark',
    'reportageLight',
    'mpva',
    'comboDeisgn',
    'customDesign',
    'phoenix548Blue',
    'phoenix548Brown',
    'minimal',
    'light',
    'scarletSails',
    'paints',
    'geometry',
    'vkaMozh',
    'mvaArtillery',
    'minimalUltra',
    'rzd',
  ],

  statuses: [
    'new',
    'photoDateApproved',
    'needAnotherPhotoDate',
    'anotherPhotoDateApproved',
    'photoDateChecked',
    'onTheFormation',
    'onDesign',
    'onEdits',
    'onProduction',
    'done',
    'closed',
  ],
}
